# Generated by Django 5.2 on 2025-04-25 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_country_of_origin'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country', verbose_name='Country of Origin'),
        ),
    ]
