# Generated by Django 5.2 on 2025-05-04 09:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': 'Ekipman Kategorisi', 'verbose_name_plural': 'Ekipman Kategorileri'},
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='equipment.equipmentcategory', verbose_name='Üst Kategori'),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='rght',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı'),
        ),
    ]
