# Generated by Django 5.2 on 2025-05-04 10:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': 'Equipment Category', 'verbose_name_plural': 'Equipment Categories'},
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='equipment.equipmentcategory', verbose_name='Parent Category'),
        ),
    ]
