# Generated by Django 5.2 on 2025-04-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaravanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name': 'Caravan Type',
                'verbose_name_plural': 'Caravan Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaravanEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_standard', models.BooleanField(default=True, verbose_name='Is Standard?')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Caravan Equipment',
                'verbose_name_plural': 'Caravan Equipments',
            },
        ),
        migrations.CreateModel(
            name='CaravanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150, verbose_name='Model Name')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Production Start Year')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Production End Year (or leave blank if current)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Length (mm)')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (mm)')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (mm)')),
                ('max_weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Weight (kg)')),
                ('berths', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Berths')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caravan_models', to='brands.brand', verbose_name='Brand')),
                ('equipments', models.ManyToManyField(blank=True, related_name='caravan_models', through='caravans.CaravanEquipment', to='equipment.equipment', verbose_name='Equipment')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caravan_models', to='caravans.caravantype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Caravan Model',
                'verbose_name_plural': 'Caravan Models',
                'ordering': ['brand__name', 'model_name'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='CaravanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caravans/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Image')),
                ('caravan_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='caravans.caravanmodel', verbose_name='Caravan Model')),
            ],
            options={
                'verbose_name': 'Caravan Image',
                'verbose_name_plural': 'Caravan Images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddField(
            model_name='caravanequipment',
            name='caravan_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravans.caravanmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='caravanequipment',
            unique_together={('caravan_model', 'equipment')},
        ),
    ]
