# Generated by Django 5.2 on 2025-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL Slug'),
        ),
    ]
